// Generated by CoffeeScript 2.3.0
(function() {
  var App;

  App = (function() {
    class App {
      static init() {
        this.copyButton.addEventListener('click', this.copy);
        this.clearButton.addEventListener('click', this.clear);
        this.ticketEdit.addEventListener('keyup', this.editListener);
      }

      static copy() {
        App.ticketDone.select();
        document.execCommand('copy');
      }

      static clear() {
        App.ticketEdit.value = '';
        App.ticketDone.value = '';
        App.changeOwner('Нет');
        App.changeStatus();
      }

      static changeStatus(element) {
        if (element === void 0) {
          element = this.manualStatus;
        }
        this.autoStatus.classList.remove('active');
        this.manualStatus.classList.remove('active');
        element.classList.add('active');
      }

      static changeOwner(number) {
        this.ownerStatus.innerHTML = number;
      }

      static manualMode(value) {
        var am, amount, comment, da, date, dateObj, dates, genDate, number, operator, terminal;
        dateObj = new Date();
        [terminal, date, amount, number, operator, comment] = value.split("\n");
        this.changeOwner(this.getOwner(terminal.split(' ')[0]));
        terminal = terminal.split(' ').join(' / ');
        if (number === void 0) {
          number = '';
        }
        if (operator === void 0) {
          operator = '';
        }
        if (amount === void 0) {
          amount = '';
        }
        number = number.split(' ').join(' / ');
        operator = operator.split(' ').join(' / ');
        if (amount === void 0) {
          amount = '';
        }
        amount = (function() {
          var i, len, ref, results;
          ref = amount.split(' ');
          results = [];
          for (i = 0, len = ref.length; i < len; i++) {
            am = ref[i];
            results.push(`${am}.00`);
          }
          return results;
        })();
        amount = amount.join(' / ');
        if (date === void 0) {
          date = '';
        }
        genDate = function(date) {
          var getDate, getFullYear, getMonth;
          getDate = dateObj.getDate();
          getMonth = dateObj.getMonth() + 1;
          getFullYear = dateObj.getFullYear();
          if (getDate < 10) {
            getDate = `0${getDate}`;
          }
          if (getMonth < 10) {
            getMonth = `0${getMonth}`;
          }
          if (date.indexOf('.') === -1) {
            return date = `${getDate}.${getMonth}.${getFullYear} ${date}`;
          } else {
            return date;
          }
        };
        dates = (function() {
          var i, len, ref, results;
          ref = date.split(' ');
          results = [];
          for (i = 0, len = ref.length; i < len; i++) {
            da = ref[i];
            results.push(genDate(da));
          }
          return results;
        })();
        dates = dates.join(' / ');
        this.ticketDone.value = this.genTicket(terminal, dates, amount, number, operator, comment, -1, -1);
      }

      static autoMode(value) {
        var amount, date, error, i, len, number, numberPattern, operator, ref, status, terminal, val, valuesArray;
        Array.prototype.unique = function() {
          var i, key, output, ref, results;
          output = {};
          for (key = i = 0, ref = this.length; (0 <= ref ? i < ref : i > ref); key = 0 <= ref ? ++i : --i) {
            output[this[key]] = this[key];
          }
          results = [];
          for (key in output) {
            value = output[key];
            results.push(value);
          }
          return results;
        };
        value = value.replace(/^\s+|\s+$/g, '');
        terminal = [];
        date = [];
        amount = [];
        number = [];
        numberPattern = /\d{6,}/;
        operator = [];
        error = '';
        status = '';
        ref = value.split("\n");
        for (i = 0, len = ref.length; i < len; i++) {
          val = ref[i];
          valuesArray = val.split(';');
          terminal.push(valuesArray[1]);
          date.push(valuesArray[2]);
          amount.push(valuesArray[6] + '.00');
          number.push(valuesArray[4].match(numberPattern));
          operator.push(valuesArray[5]);
          status = valuesArray[9];
          error = valuesArray[10];
        }
        terminal = terminal.unique();
        this.changeOwner(this.getOwner(terminal[0]));
        date = date.unique();
        number = number.unique();
        operator = operator.unique();
        terminal = terminal.join(' / ');
        date = date.join(' / ');
        amount = amount.join(' / ');
        number = number.join(' / ');
        operator = operator.join(' / ');
        this.ticketDone.value = this.genTicket(terminal, date, amount, number, operator, '', status, error);
      }

      static getStatus(val) {
        var i, len, ref, status;
        ref = this.statuses;
        for (i = 0, len = ref.length; i < len; i++) {
          status = ref[i];
          if (status.indexOf(`Статус=${val}`) !== -1) {
            return status;
          }
        }
        return '';
      }

      static getError(val) {
        var error, i, len, ref;
        ref = this.errors;
        for (i = 0, len = ref.length; i < len; i++) {
          error = ref[i];
          if (error.indexOf(`Ошибка=${val}`) !== -1) {
            return error;
          }
        }
        return '';
      }

      static editListener() {
        var value;
        value = App.ticketEdit.value;
        if (value.indexOf(';') !== -1) {
          App.changeStatus(App.autoStatus);
          App.autoMode(value);
        } else {
          App.changeStatus(App.manualStatus);
          App.manualMode(value);
        }
      }

      static getOwner(terminal) {
        var i, len, ref, val;
        ref = this.owners;
        for (i = 0, len = ref.length; i < len; i++) {
          val = ref[i];
          if (val.split(':')[0] === terminal) {
            return val.split(':')[1];
          }
        }
        return 'Нет';
      }

      static genTicket(terminal = '', date = '', amount = '', number = '', operator = '', comment = '', status, error) {
        status = this.getStatus(status);
        error = this.getError(error);
        return `Терминал: ${terminal}\nДата/время: ${date}\nСумма: ${amount}\nНомер счета/телефона: ${number}\nВерный номер счета/телефона:\nСервис/Оператор: ${operator}\nВерный Сервис/Оператор:\nКомментарий: ${comment}\n${status}\n${error}`;
      }

    };

    App.ticketEdit = document.querySelector('#ticketEdit');

    App.ticketDone = document.querySelector('#ticketDone');

    App.copyButton = document.querySelector('#copyButton');

    App.clearButton = document.querySelector('#clearButton');

    App.autoStatus = document.querySelector('#autoStatus');

    App.manualStatus = document.querySelector('#manualStatus');

    App.ownerStatus = document.querySelector('#ownerStatus');

    App.owners = ['87654491:9057765572', '354:9250511492', '15121045:9150305000', '495:9264300299', '9888549:9060965746', '314:9640088004', '513:9264300299', '9887417:9250511492', '496:9264300299', '552:9640088084', '9888542:9269174337', '8765476:87654761', '399:9803431231', '107:9129762003', '87654958:9851421603', '9458936:9285551027', '87654401:9626461645', '497:9264300299', '343:9288013005', '889522:9289414041', '109:9129762003', '87654781:9207891111', '400:9803431231', '87654878:9285049405', '15121205:9647894278', '87654490:9057765572', '9887645:9212056430', '225:9260152710', '9887454:9653376277'];

    App.statuses = ['Статус=0 (Ожидание проведения)', 'Статус=7 (Платеж завершен)', 'Статус=1 (Платеж проводится)', 'Статус=100 (Платеж не проведен)', 'Статус=108 (Платеж проведен вручную)', 'Статус=120 (Платеж заблокирован при обработке)', 'Статус=112 (Платеж проведен оффлайн)', 'Статус=102 (Платеж отменен вручную)', 'Статус=103 (Запрос на ручную отмену платежа)'];

    App.errors = ['Ошибка=3003 (Превышен дневной лимит)', 'Ошибка=1200200 (Откат транзакции)', 'Ошибка=1200500 (Откат транзакции)', 'Ошибка=1220110 (Оплата в пользу сервис-провайдера невозможна)', 'Ошибка=1220140 (Ошибочный номер абонента)', 'Ошибка=1220117 (Недостаточно средств на счету дилера для проведения этого платежа)', 'Ошибка=1200002 (Состояние платежа неизвестно, сбой при осуществлении платежа в биллинг провайдера (в последствии состояние будет изменено на проведен или на один из откатов))', 'Ошибка=53 (Точка заблокирована)', 'Ошибка=1220002 (Платеж в обработке)', 'Ошибка=1200300 (Недостаточно денег на счете дилера)', 'Ошибка=1220103 (Не найдена касса, соответствующая этому пользователю)', 'Ошибка=1220000 (Платеж в очереди)', 'Ошибка=2002 (Сетевая ошибка)'];

    return App;

  }).call(this);

  App.init();

}).call(this);

//# sourceMappingURL=core.js.map
